"""
Django settings for comunidade project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

from .seguranca import chave_secreta, hosts_permitidos

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Raiz do repositório: o .env e o banco do bot moram um nível acima de web/.
PROJECT_ROOT = BASE_DIR.parent

load_dotenv(PROJECT_ROOT / ".env")

# O padrão é produção. Esquecer de definir a variável no servidor precisa
# resultar em site seguro e quebrado, nunca em site aberto e funcionando: com
# DEBUG ligado qualquer visitante vê traceback com settings e trecho de banco.
# Na sua máquina, ponha DJANGO_DEBUG=1 no .env.
DEBUG = os.getenv("DJANGO_DEBUG", "0") == "1"

# `manage.py test` importa este arquivo, e exigir credencial de produção só
# para rodar o suite atrapalharia sem proteger nada — o teste não serve
# tráfego. As duas exigências abaixo continuam valendo para qualquer processo
# que atenda requisição.
RODANDO_TESTE = "test" in sys.argv
LOCAL = DEBUG or RODANDO_TESTE

SECRET_KEY = chave_secreta(os.getenv("DJANGO_SECRET_KEY", ""), LOCAL)

ALLOWED_HOSTS = hosts_permitidos(os.getenv("DJANGO_ALLOWED_HOSTS", ""), LOCAL)

# Precisa incluir o esquema: `https://ofertas.seudominio.com.br`. Sem isso o
# POST do formulário de e-mail leva 403 atrás de HTTPS, e o único caminho de
# conversão de quem chega com os grupos lotados morre calado.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# ---------- HTTPS ----------

# O proxy (Caddy) termina o TLS e fala HTTP com o Django. Sem ler o cabeçalho,
# `request.is_secure()` dá False, o redirect de HTTPS entra em laço infinito e
# as URLs absolutas do preview de link saem com http://.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Ligue (DJANGO_HTTPS=1) somente quando já existir certificado na frente.
# Redirecionar para HTTPS sem TLS deixa o site inalcançável.
HTTPS = os.getenv("DJANGO_HTTPS", "0") == "1"
SECURE_SSL_REDIRECT = HTTPS
SESSION_COOKIE_SECURE = HTTPS
CSRF_COOKIE_SECURE = HTTPS

# O healthcheck fica de fora do redirect, e sem isso o site quebra o próprio
# monitoramento no dia em que o TLS entra.
#
# O healthcheck do compose chama `http://127.0.0.1:8001/saude/` de dentro do
# container, onde não existe TLS nenhum -- quem termina o certificado é o
# Caddy, do lado de fora. Com o redirect valendo aqui, a sonda recebe 301 para
# https://127.0.0.1:8001/, segue, e morre em "handshake operation timed out".
# O container vira `unhealthy` para sempre e o portão de saúde do deploy
# reprova uma publicação que está de pé.
#
# Isolar este caminho não abre brecha: a porta 8001 não é publicada, só o Caddy
# alcança o gunicorn, e o `/saude/` devolve contadores -- nenhum segredo.
SECURE_REDIRECT_EXEMPT = [r"^saude/$"]

# HSTS começa curto de propósito. O navegador guarda o prazo que recebeu e
# não há como encurtá-lo depois: se o certificado falhar com um ano gravado,
# o domínio fica inacessível por um ano. Suba para 31536000 depois de uma
# semana de TLS estável.
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", "3600" if HTTPS else "0"))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # intcomma nos números da landing
    "vitrine",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise entra logo depois do security e ANTES de todo o resto.
    # Motivo concreto: o servidor de estáticos do runserver responde 200 com
    # o arquivo inteiro e ignora `Range`. Sem resposta 206 o navegador não
    # consegue saltar dentro do vídeo, `currentTime` não anda, e o Scroll
    # Cinema congela no primeiro quadro. WhiteNoise fala Range, e é também
    # o que vai servir os estáticos em produção.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Limite de tentativas no login do admin. Depois do Authentication
    # porque precisa do `request.user` para saber se o login deu certo.
    "comunidade.seguranca.LimiteDeLoginMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # CSP e Permissions-Policy. Ver comunidade/cabecalhos.py.
    "comunidade.cabecalhos.seguranca",
]

# Referer completo vaza a página exata que o visitante estava lendo para o CDN
# da loja e para o Google Fonts. Só a origem é suficiente.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

ROOT_URLCONF = "comunidade.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # URL canônica e imagem de preview de link em toda página.
                "vitrine.context.meta",
            ],
        },
    },
]

WSGI_APPLICATION = "comunidade.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # Banco do site (grupos e inscritos). Mora no mesmo volume do histórico de
    # preço porque dentro da imagem Docker `web/db.sqlite3` é apagado a cada
    # `up --build` — e levaria os grupos cadastrados e os e-mails junto.
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": PROJECT_ROOT / os.getenv("DJANGO_DB_PATH", "data/site.db"),
        # Vários workers do gunicorn escrevendo inscrição no mesmo arquivo:
        # WAL para leitor e escritor não se bloquearem, e espera pelo lock em
        # vez de 500 na cara de quem acabou de deixar o e-mail.
        "OPTIONS": {"timeout": 20, "init_command": "PRAGMA journal_mode=WAL;"},
    },
    # Banco do bot, montado somente para leitura. O caminho acompanha o
    # DB_PATH que o coletor usa, então os dois falam do mesmo arquivo.
    "promos": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": PROJECT_ROOT / os.getenv("DB_PATH", "data/promos.db"),
        "OPTIONS": {
            "transaction_mode": "DEFERRED",
            # A coleta escreve neste arquivo enquanto o site o lê. O bot deixa
            # o banco em WAL (ver promo.db.connect), então leitor e escritor
            # não se bloqueiam — mas um checkpoint do WAL ainda pode segurar a
            # leitura por instantes. Sem timeout o driver levanta na hora, e o
            # `_seguro()` das views transformaria isso numa home com contador
            # zerado, com status 200 e sem log.
            "timeout": 20,
        },
        "TEST": {"MIRROR": "default"},
    },
}

DATABASE_ROUTERS = ["comunidade.routers.PromosRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

# "R$ 1349,00" lê como quatro algarismos soltos; num site cujo argumento é
# preço, o separador de milhar é legibilidade, não enfeite. Com isto ligado,
# `floatformat` já sai como "R$ 1.349,00" no locale pt-BR e o `intcomma` do
# humanize deixa de ser necessário (ele usa vírgula e brigaria com a vírgula
# decimal, produzindo "1,349,00").
#
# Cuidado ao ler número em atributo HTML: `data-contar="{{ n }}"` também é
# localizado, e `Number("1.234")` em JavaScript dá 1,234. Onde o valor é lido
# por script, o template usa `{% localize off %}`.
USE_THOUSAND_SEPARATOR = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Em produção o nome do arquivo leva o hash do conteúdo, então cache de um ano
# é seguro e um deploy novo nunca serve CSS velho. Em DEBUG o armazenamento
# simples evita depender de `collectstatic` para cada alteração.
# O manifesto só existe depois de um `collectstatic`, e o suite não roda um —
# com ele ligado, todo `{% static %}` do teste estouraria
# "Missing staticfiles manifest entry" e a falha não diria nada sobre o site.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if LOCAL
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        )
    },
}

# Localmente o WhiteNoise precisa dos finders para achar os arquivos sem
# um `collectstatic` prévio. Em produção ele serve o STATIC_ROOT, que é o
# único lugar onde os nomes com hash existem.
WHITENOISE_USE_FINDERS = LOCAL
# O vídeo do hero é grande e imutável; sem isso o navegador rebaixa o
# arquivo inteiro a cada visita.
WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------- Backoffice: falar com o bot ----------
# A tela de oferta da Amazon não escreve no banco do bot; ela chama a API dele.
# O roteador em `comunidade/routers.py` proíbe essa escrita de propósito, e a
# regra não abre exceção para o backoffice.
#
# Dentro da rede do compose o host é o nome do serviço. O `ports` do
# amazon_pay publica só em 127.0.0.1, então de fora ninguém alcança.
BOT_API_URL = os.getenv("BOT_API_URL", "http://amazon_pay:8000")
# A mesma API_SECRET que o bot exige no header X-API-Key. Sem ela a tela
# recebe 503 do próprio bot, que é o comportamento certo: melhor recusar do
# que enfileirar sem autenticação.
BOT_API_SECRET = os.getenv("API_SECRET", "")

# ---------- Cache ----------
# Em ARQUIVO, e não o LocMemCache padrão, porque o gunicorn roda com vários
# workers e o LocMemCache vive dentro de UM processo.
#
# Medido em produção em 07/09/2026: com LocMemCache, 30 tentativas seguidas de
# login erradas no mesmo IP passaram todas — nenhuma 429. O contador existia,
# mas cada worker tinha o seu, e nenhum chegou ao limite de 8. A mesma lógica
# testada isoladamente bloqueia certo na nona. Ou seja: a proteção estava
# instalada e não protegia, sem sintoma nenhum.
#
# O diretório fica no volume `data/`, que já é persistente e é o único lugar
# gravável entre reinícios do container.
#
# O custo é uma leitura de arquivo por acerto de cache, contra um dicionário em
# memória. Para o volume deste site — o contador de tentativas e um resumo de
# números da home, com 60 segundos de vida — isso não aparece em lugar nenhum,
# e o que se ganha é um contador que realmente conta.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": str(PROJECT_ROOT / os.getenv("DJANGO_CACHE_DIR", "data/cache")),
        "TIMEOUT": 300,
        "OPTIONS": {"MAX_ENTRIES": 1000},
    }
}

# ---------- Tentativas de login no admin ----------
# O /admin/ está exposto na internet e a senha é a única barreira. Sem limite,
# uma lista de senhas comuns roda a noite inteira sem custo nenhum para quem
# tenta. Ver comunidade/seguranca.py.
LOGIN_MAX_TENTATIVAS = int(os.getenv("LOGIN_MAX_TENTATIVAS", "8"))
LOGIN_BLOQUEIO_MINUTOS = int(os.getenv("LOGIN_BLOQUEIO_MINUTOS", "15"))
