# Generated by Django 5.2.17 on 2026-08-20 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricoPreco",
            fields=[
                ("product_id", models.TextField(primary_key=True, serialize=False)),
                ("observed_on", models.TextField()),
                ("price", models.FloatField()),
                ("original_price", models.FloatField(null=True)),
                ("available", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "price_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.TextField()),
                ("price", models.FloatField()),
                ("baseline", models.FloatField()),
                ("discount_pct", models.FloatField()),
                ("copy", models.TextField()),
                ("image_url", models.TextField(null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("status", models.TextField()),
                ("error", models.TextField(null=True)),
                ("created_at", models.TextField()),
                ("sent_at", models.TextField(null=True)),
            ],
            options={
                "db_table": "posts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("source", models.TextField()),
                ("external_id", models.TextField()),
                ("title", models.TextField()),
                ("url", models.TextField()),
                ("image_url", models.TextField(null=True)),
                ("category", models.TextField(null=True)),
                ("first_seen_at", models.TextField()),
                ("last_seen_at", models.TextField()),
            ],
            options={
                "db_table": "products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                (
                    "convite",
                    models.URLField(
                        help_text="URL chat.whatsapp.com gerada no próprio grupo",
                        verbose_name="link de convite",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Geral, Eletrônicos, Casa. Vazio = grupo geral",
                        max_length=40,
                    ),
                ),
                ("membros", models.PositiveIntegerField(default=0)),
                ("capacidade", models.PositiveIntegerField(default=1024)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Menor primeiro. Define qual grupo recebe as entradas.",
                    ),
                ),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "grupos",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="Inscrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("origem", models.CharField(blank=True, max_length=40)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
