# Generated by Django 5.2.17 on 2026-08-23 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='jid',
            field=models.CharField(blank=True, help_text='Termina em @g.us. Sai do `promo wa-groups`. Com ele preenchido, o comando `sincronizar_grupos` atualiza o número de membros sozinho.', max_length=80, verbose_name='JID do WhatsApp'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='membros_atualizados_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Clique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('topo', 'barra do topo'), ('cinema', 'filme de abertura'), ('hero', 'chamada principal'), ('grupos', 'cartão do grupo'), ('oferta', 'página de oferta'), ('desconhecida', 'sem origem declarada')], default='desconhecida', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('grupo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliques', to='vitrine.grupo')),
            ],
            options={
                'verbose_name_plural': 'cliques',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['criado_em'], name='vitrine_cli_criado__ae695f_idx')],
            },
        ),
    ]
